#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* This function is responsible for moving the robot forward or backward based
   on the input given. Also the run time fo the program depends on the input */

void movementRobot(int speed, long int runTime) {
	motor[motorB] = speed;
	motor[motorC] = speed;
	wait1Msec(runTime);
}

/* This Function is responsible for following the red line avoiding the pattern
	 used touch sensor to find out th end point of the line. Speed set 25 as slow
	 speed ensure obstaclaes prevent and also prevent robot from flying away from
	 the red line. IF, Else used for left right movement of the robot */

void redLineFollow () {
	while(SensorValue(touchSensor) == 0) {
	  if (getColorName(S3) == colorRed){
	  	motor[motorB] = 25;
	  	motor[motorC] = 0;
	  }
	  else {
	    motor[motorB] = 0;
	    motor[motorC] = 25;
	  }
	}
}

/* This Function is responsible for following the red line after coming back
   from the Entry area and this run for 27 seconds as after that time it reaches
   near the end of the red line */

void redLineFollowBack () {
	ClearTimer(T1);
  while(time1[T1] < 27000) {
	  if (getColorName(S3) == colorRed){
	  	motor[motorB] = 20;
	  	motor[motorC] = 0;
	  }
	  else {
	    motor[motorB] = 0;
	    motor[motorC] = 20;
	  }
	}
}

/* This function is responsible for giving pause after execution for better
	 functionality of motor */

void pauseMovement() {
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(1000);
}

/* This function alters the left & right movement of the robot based on input.
   Even excution time depends on input provided */

void robotTurn(int speed1, int speed2, int time) {
	setMotorSpeed(motorB, speed1);
	setMotorSpeed(motorC, speed2);
	sleep(time);

}

/* Main Starts Here */

task main()
{
/* This Moves the robot straight till it touches LEGO BOX and stops on encounter */
	while(SensorValue(touchSensor) == 0) {
		motor[motorB] = 50;
		motor[motorC] = 50;
	}

/* Moving Back after Hitting the lego box in order to allign itself with red line */
	movementRobot(-30, 1600);
	pauseMovement();

/* Turning from facing LEGO Box towards Red line */
	robotTurn(0, 50, 750);
	pauseMovement();

/* Moving Robot forwads a bit close to Red line  */
	movementRobot(30,1100);
	pauseMovement();

/* Following Red Line Function Called */
	redLineFollow();
	pauseMovement();

/* After Bumping after hitting the wall after following the red line. Move Backwards
  and then performing a Turn to enter the box */
	movementRobot(-50, 200);
	robotTurn(-50,0,900);
	pauseMovement();

/* Moving backwards to enter the box */
	movementRobot(-60, 1500);

/* After Going in then coming out near the red line to follow again */
	movementRobot(60,1000);

/* Following the red Line in order to reach the end of the circuit */
	redLineFollowBack();
  pauseMovement();

/* After 27 sec Robot performs a turn to enter at its Final Destination*/
	robotTurn(0, 40, 400);
	movementRobot(100, 1100);

}
